### ISSUE TITLE
Hacked

### ISSUE THREAD

**Issue by Bellagina1975** [GO-SOPT-ANDROID/chaeyeon-jeon#4]
Me amd my family have beem being hacked simce June 2021 by this man Steven Losada he has stolen our identities using this coding system and misusing licenses, he has stolen our money, breached our data, credit card companys, he has stolen over $30,000 dollars from us" ruined our credit, my childrens credit, please Github help us stop him, he is the one who breached Verizon and is still doing it. I need help 

> please`
/` # @

**Comment by Bellagina1975** [comment]
Please githun this is a serius matter that neefs swift avtion taken

**Comment by b1urrrr** [comment]
My repository is not shinmungo

**Comment by Bellagina1975** [comment]
Im learning
